### ISSUE TITLE
Simple example for Arduino

### ISSUE THREAD

**Issue by mralexgray** [pimoroni/unicorn-hat#48]
I know it is possible... but I have been too dumb to figure out what is needed (libraries, etc) / how to connect the hat - to an Arduino - for simple usage.

Any example / help would be much appreciated!

**Comment by Gadgetoid** [comment]
You can use Adafruit's NeoPixel library to drive UnicornHAT from an Arduino. Use the VCC, DIN and GND pins on the edge of UnicornHAT to connect to 5V, a data pin, and Ground respectively and you're good to go: https://learn.adafruit.com/adafruit-neopixel-uberguide/arduino-library

**Comment by xTauv** [comment]
Gadgetoid, I'm really new to this. So I want to attach the UnicornHAT to an Arduino Uno. Could you simplify the adafruit NeoPixel code for me? I'm very confused.
- Thanks!

**Comment by xTauv** [comment]
![image1](https://user-images.githubusercontent.com/33187797/32139592-faf7a61a-bc01-11e7-8aae-f4f46366dde7.jpeg)

Should I use the NeoMatrix library instead?

**Comment by Gadgetoid** [comment]
Looks like you're wiring the right pins to the right connections on the HAT, but without a more robust connection you'll probably find it doesn't work. Since the ends of those wires are square, and the holes on the PCB are round, the contact surface is at best negligible.

You can either:

a. Solder the wires, or a female header to the Unicorn HAT to make a better connection
or
b. Plug the wires directly into the relevant connections on the 40-pin header. See: https://pinout.xyz/pinout/unicorn_hat which gives a top down view of which pins to use (looking from the top of the HAT)

Then to init the library on Arduino:

```arduino
#include <Adafruit_NeoPixel.h>
#define PIN 6
Adafruit_NeoPixel strip = Adafruit_NeoPixel(64, PIN, NEO_GRB + NEO_KHZ800);
void setup() {
  strip.begin();
  strip.show(); // Initialize all pixels to 'off'
  strip.setPixelColor(11, 255, 0, 255); 
  strip.show();
}
void loop() {
  // put your main code here, to run repeatedly:
}
```
